### ISSUE TITLE
Missing auth backend in configuration.py

### ISSUE THREAD

**Issue by riimak** [lae/ansible-role-netbox#107]
I believe there is a missing parameter in configuration.py if you want to have LDAP as a authentication backend. [Docs](https://netbox.readthedocs.io/en/stable/installation/6-ldap/) about configuration are mentioning if you want LDAP as auth backend to add the line in the configuration.py:

`REMOTE_AUTH_BACKEND = 'netbox.authentication.LDAPBackend'`

I cannot find this in any of your versions, any thoughts?

**Comment by lae** [comment]
That variable was introduced in NetBox 2.9.1: https://github.com/netbox-community/netbox/releases/tag/v2.9.1. I've yet to process through the changelogs and make updates to this role for 2.9.

Since it's a configuration variable however, you can configure this in the `netbox_config` role variable.

For NetBox 2.8 documentation, you can check out https://github.com/netbox-community/netbox/blob/v2.8.9/docs/installation/5-ldap.md.

**Comment by riimak** [comment]
Ok,thanks!
