### ISSUE TITLE
Add option to enable webhooks

### ISSUE THREAD

**Issue by madeinoz67** [lae/ansible-role-netbox#37]
Webhooks are not enabled by default with netbox install so additional packages and configuration is required
(as per https://netbox.readthedocs.io/en/latest/installation/2-netbox/#webhooks-configuration)

install redis
install django-rq via pip

addition configuration required
```
WEBHOOKS_ENABLED = True
REDIS = {
    'HOST': 'localhost',
    'PORT': 6379,
    'PASSWORD': '',
    'DATABASE': 0,
    'DEFAULT_TIMEOUT': 300,
}
```

**Comment by lae** [comment]
I wasn't actually sure if you wanted to work on this so I had started some work (not much though) - but since you opened a PR, I've gone ahead and assigned it to you.

**Comment by lae** [comment]
Looks like setting up the `rq-worker` service is missing per https://netbox.readthedocs.io/en/stable/installation/3-http-daemon/#supervisord-installation

@madeinoz67 do you want to punch this one out? Would need a new systemd unit (see `netbox.service.j2`) only (and no socket since it's not a web service or w/e), from the brief reading I did.

More documentation (probably not relevant though): https://github.com/rq/django-rq#running-workers

**Comment by madeinoz67** [comment]
yes will look at this later today if not tomorrow

**Comment by madeinoz67** [comment]
@lae How do you currently run your tests locally?  

Have you considered moving to molecule for testing?

**Comment by lae** [comment]
I use Vagrant. I don't use Molecule because its boilerplate is excessive and I don't consider Docker images to be representative of systems most people would use Ansible roles on, e.g. missing systemd (as opposed to LXC setups).

```
[lae@yuzu ansible-role-netbox]$ git archive --format tar.gz HEAD > lae.netbox.tar.gz && ansible-galaxy install --force lae.netbox.tar.gz,$(git rev-parse HEAD),lae.netbox && rm lae.netbox.tar.gz
- changing role lae.netbox from 7ba458247afe986b63eaf991d086cefcf4b40cef to fcb92e687aa247143576805b7f0219fabd0a12b1
- extracting lae.netbox to /home/lae/.ansible/roles/lae.netbox
- lae.netbox (fcb92e687aa247143576805b7f0219fabd0a12b1) was installed successfully
[lae@yuzu ansible-role-netbox]$ vagrant up
<blah blah>
<ansible role runs>
```

It uses the example playbook in `examples` as-is, hence the git archive step to install the role, but I guess this could be improved to use the current directory somehow. I don't often test locally.
