### ISSUE TITLE
Forcing the role to use Python 3 breaks deployment on CentOS/RHEL 7

### ISSUE THREAD

**Issue by eburgueno** [lae/ansible-role-netbox#47]
As shown in https://github.com/ansible/ansible/issues/53929, by forcing Ansible to use Python 3 as the interpreter causes the role to break at any template task.

Is there a reason using Python 3 for Ansible is enforced?

**Comment by lae** [comment]
NetBox/Django doesn't support Python 2 anymore. There are several tasks in the role that require to be run as Py3 where there would need to be extra boilerplate in order to support Ansible running under both Python 2 and 3 and supporting both also doubles the time it takes for CI tests to complete - which I don't think is a good tradeoff.

I'd expect you could add selinux to the list in the pip preparation task here to resolve this issue however: https://github.com/lae/ansible-role-netbox/blob/master/tasks/install_packages_yum.yml#L29

Can you try that and report back?

**Comment by eburgueno** [comment]
I'm pretty sure we can do away with some of the interpreter logic and simplify the role. `python36-pip` is already in EPEL so you we can use that to create the `venv`, and we would only need `python-psycopg2` for the ansible `postgres*` modules.

This will also help making the role ready for when ansible 2.8 comes out, that promises to auto-detect the interpreter (not sure how that's going to work yet).

I'll try and make some changes and send a PR your way soon.

**Comment by eburgueno** [comment]
I managed to remove all instances of `ansible_python_interpreter`, but we'd need to stick to using `uwsgi` from repos. It is present in all distributions:

Debian 9: 
```
# uwsgi --version
2.0.14-debian
```

Ubuntu 16:
```
# uwsgi --version
2.0.12-debian
```

Ubuntu 18:
```
# uwsgi --version
2.0.15-debian
```

RHEL/CentOS 7 (note, it also requires `uwsgi-logger-file` to be installed. Also available from EPEL)
```
# uwsgi --version
2.0.17.1
```

Would this be acceptable to you?

**Comment by lae** [comment]
If I recall correctly, installing `uwsgi` from repositories involves more steps than just installing the `uwsgi` package (e.g. installing `uwsgi-python` for python support) and I think it also is packaged for Python 2 in all distros currently (not sure)? (and I'd like to avoid requiring Python 2+dependencies on the system if possible.) I vaguely recall that packaged uwsgi was not enough at the time of writing the role, thus prompting me to use pip in the role instead, but maybe the situation has gotten better since then.

There is also the catch that existing NetBox installations using this role currently do *not* have packaged uwsgi installations, so an upgrade in the role would require removal of it - and I'm still not convinced (having read the referenced issue) that this issue warrants such a big change. Can you try the suggestion in my earlier comment of installing the selinux library via pip?

**Comment by lae** [comment]
Was able to reproduce issue using Vagrant - the solution I suggested earlier works fine.
