### ISSUE TITLE
Add an option to specify custom python3 requirements for virtualenv

### ISSUE THREAD

**Issue by smutel** [lae/ansible-role-netbox#92]
Hello,

Currently I am using netbox reports which are using the DNS python library.
So I need to install this python library directly in the netbox virtualenv.
I saw this variable `netbox_pip_constraints` which is in a template but there is not task to install this template.
When we will agree with this feature, I am able to implement it if you want.

Regards.

**Comment by kdhlab** [comment]
The `netbox_pip_constraints` gets utilized during the virtualenv creation, but it doesn't actually install anything it just is for forcing certain versions of packages to be installed.

`netbox_plugins` will do what you are looking for.

**Comment by lae** [comment]
`netbox_plugins` hasn't been merged to master yet (it's part of the 2.8 feature branch).

I'm thinking that maybe it may be best to just rename that role variable to be all-encompassing and just update the docs to reflect that.

**Comment by smutel** [comment]
I think that `netbox_plugins` will be used to install netbox plugins (https://netbox.readthedocs.io/en/stable/plugins/development/).

What about to have a `pip_custom_requirements` ?

**Comment by lae** [comment]
Yes, `netbox_plugins` was originally meant to just install netbox plugins (see https://github.com/lae/ansible-role-netbox/pull/87/commits/f7a8ff58025c3f122d96d714ee4a187c2c249dbf). However, it just accepts package names to be installed via pip, which is basically what you're asking for, and as such I was suggesting renaming that to be more generic (because it isn't part of any release yet) so that we don't have two variables that basically do the same thing.

**Comment by smutel** [comment]
Sounds good.

Two questions:
* Do you want I do a merge request to the 2.8 branch ?
* Do you think the 2.8 version will released soon ?

**Comment by lae** [comment]
- I'm going to force-push an amended commit, so I can take care of this and the doc updates needed.
- I just need a confirmation that upgrading from 2.7 to 2.8 works fine - I may get to this soon (I don't have access to an existing install currently so I need to make one), but if anyone else confirms it, it'll be merged and released.
