### ISSUE TITLE
SVG not showing

### ISSUE THREAD

**Issue by thefactor82** [lae/ansible-role-netbox#99]
Hi everyone,
I've just upgraded my Netbox to 2.8.4 version via lae role, and now seems that SVG images are not working anymore...

Could you please suggest me something?
<img width="231" alt="2020-05-20 10_25_02-Home - NetBox" src="https://user-images.githubusercontent.com/30239971/82423591-40b22a00-9a84-11ea-9d57-94149bcb5114.png">

**Comment by lae** [comment]
1. Are you using v1.0.0rc1 of the role?
2. Did you have any errors when running the playbook? Specifically on the task `Generate static assets for NetBox`?
3. What happens when you run `cd /srv/netbox/current; source venv-py3/bin/activate; ./netbox/manage.py collectstatic`? (this is off the top of my head, the locations might be different so double check yourself)

**Comment by thefactor82** [comment]
1. Yes, I used v1.0.0rc1 to fix the REDIS webhooks renamed to tasks  problem...
2. No problem at all on this task
3. This is the output of the command:
(venv-py3) [root@netboxhost current]# ./netbox/manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /srv/netbox/releases/netbox-2.8.4/netbox/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes

0 static files copied to '/srv/netbox/releases/netbox-2.8.4/netbox/static', 976 unmodified.

**Comment by thefactor82** [comment]
If it can be of any help, inspecting the web page I can see this:
![image](https://user-images.githubusercontent.com/30239971/82425352-adc6bf00-9a86-11ea-82ca-5285371b6606.png)

**Comment by lae** [comment]
Was just about to ask for something like that. Can you check the Network tab and see what's 404ing?

This is probably going to be an issue to check the mailing list about if you haven't already (and possibly ask there).

**Comment by pugnacity** [comment]
I've the same problem with Safari, but for what ever reason firefox will show the SVG. It looks more like a NetBox problem.

**Comment by thefactor82** [comment]
For some reasons that I cannot understand (I'm not a web developer)
![image](https://user-images.githubusercontent.com/30239971/82426835-a1dbfc80-9a88-11ea-8485-31f7138a7c19.png)

The svg logo gives a 200 response...

**Comment by lae** [comment]
Based on what Sven said - does it work fine for you if you try a different browser? If it does, I'd recommend opening a thread on the netbox-discuss mailing list.

It does look like the SVG logo was introduced in NetBox 2.6.10 though, so unless you were upgrading from a version older than that then idk why it'd only break now.

**Comment by thefactor82** [comment]
Actually, my upgrade path was starting from Netbox 2.5.2!
I've done 2.5.2 -> 2.5.13 -> 2.6.0 -> 2.6.12 -> 2.7.0 -> 2.7.12 -> 2.8.4
So it is possibile that I've not noticed this problem before... But I'm sure that on 2.5.2 was working...

And I confirm that Firefox is working.
Chrome, Edge and Opera not working

**Comment by lae** [comment]
The icon was a PNG in 2.5.2, which definitely shouldn't be a problem in any browser. It was switched to an SVG in 2.6.10. Anyway, post in the mailing list (or NetBox' Github issues tracker) about this, since it seems you and Sven have this issue.

Closing since it doesn't seem to be related to the Ansible role, but if that doesn't turn out to be the case feel free to reopen (with more information).

**Comment by espro** [comment]
This issue is due to `uwsgi` not having the correct MIME types

On RHEL distros this can be fixed by installing the `mailcap` package and then changing the `/usr/lib/systemd/system/netbox.service` `ExecStart` parameter to `/usr/bin/env uwsgi --ini /srv/netbox/shared/uwsgi.ini --mimefile=/etc/mime.types`

I would provide a pull request but I don't have the time to look into other distributions like Debian, though I believe the `mime-support` package is what you want there, and `uwsgi` may correctly load that without the extra argument.
